version: '3.8'

services:
  cron-service:
    build: .
    container_name: guess-game-cron
    env_file:
      - config.env
    environment:
      - INNO_API_URL=${INNO_API_URL:-http://host.docker.internal:3000}
      - CRON_SECRET=${CRON_SECRET}
      - PORT=3002
      - NODE_ENV=production
    ports:
      - "3002:3002"
    volumes:
      - ./logs:/app/logs
      - ./config.env:/app/config.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - inno-network

networks:
  inno-network:
    external: true
    name: inno-network
